#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# Link DisplayLink providers to NVIDIA (adjust IDs from xrandr --listproviders)
xrandr --setprovideroutputsource 1 0 2>/dev/null

# Small delay to let DisplayLink settle
sleep 1

# Extend displays on WM startup
xrandr --output eDP-1 --auto --output DVI-I-3-2 --right-of eDP-1 --auto --output DVI-I-2-1 --left-of eDP-1 --auto

# Desktop background image
feh --bg-fill /usr/share/pixmaps/background.jpg &

exec dwm 2>~/Documents/dwm.log
